### ISSUE TITLE
How to make it work with streams from streamtheworld ?

### ISSUE THREAD

**Issue by frequeradio** [ghaiklor/icecast-parser#115]
Hi !

When i try to use icecast parser with various strem, for example from streamtheworld : http://20073.live.streamtheworld.com/LOS40_SC   i don't have any result

what am i doing wrong ?

thanks

**Comment by ghaiklor** [comment]
Hi @frequeradio,

There are some radiostations that don't stream its metadata or stream it in different protocol, that does not supported by this module.

**Comment by ghaiklor** [comment]
You should try it on radiostations from examples to confirm that you have working installation

**Comment by frequeradio** [comment]
With some stations it's working fine, but many have this issue.
Do you know a library that could work ?

**Comment by ghaiklor** [comment]
@frequeradio no

As I said before, there are possible reasons for it and I believe you are just passing streams that do not have this metadata. Shoutcast and Icecast are the most popular formats for such cases, so it is most likely you are trying to parse metadata from the stream that does not have it.

**Comment by ghaiklor** [comment]
I was passing through old issues and found this one. Checked it again and it I see that it works as expected on the latest update.

<img width="1904" alt="Screen Shot 2020-09-20 at 15 20 38" src="https://user-images.githubusercontent.com/3625244/93711171-dd7cf500-fb54-11ea-991d-6b86f087e781.png">
