### ISSUE TITLE
Unable to parse Radio Paradise stream

### ISSUE THREAD

**Issue by carylewis** [ghaiklor/icecast-parser#158]
This code fragment does not work:

```js
const Parser = require('icecast-parser');
const radioStation = new Parser('http://stream-dc1.radioparadise.com:80/ogg-96m');

radioStation.on('metadata', function(metadata) {
    console.log([metadata.StreamTitle, 'is playing on', this.getConfig('url')].join(' '));
});
```

But inside the stream I do see:

```
server=Icecast 2.4.0-kh13
```

I was just wondering if this was supposed to work?

**Comment by ghaiklor** [comment]
You are trying to get `StreamTitle` from the stream where only `server` field is present. What you expected to get?

**Comment by carylewis** [comment]
The stream does have artist and title in it - but obviously not in the
format that your code is expecting.

Here is a small snippet.

The sox play command can display the artist and title while playing the
stream, so there must be a specification for icecast 2.4.0-kh13?

OggS^@^B^@^@^@^@^@^@^@^@£^?Ü@^@^@^@^@¶&M×^A^^^Avorbis^@^@^@^@^BD¬^@^@^@w^A^@^@w^A^@^@w^A^@¸^AOggS^@^@^@^@^@^@^@^@^@^@£^?Ü@^A^@^@^@<93>ë7%^P<93>ÿÿÿÿÿÿÿÿÿÿÿÿÿÿâ^Cvorbis,^@^@^@Xiph.Org
libVorbis I 20150105
(â<9b><84>â<9b><84>â<9b><84>â<9b><84>)^C^@^@^@^N^@^@^@artist=Guster
$^@^@^@title= Come Downstairs and Say Hello^Y^@^@^@server=Icecast
2.4.0-kh13^A^Evorbis%BCV^A^@@^@^@$s^X*F¥s^V<84>^P^ZBP^Yã^\BÎkì^YBL^Q<82>^\2L[Ë%s<90>!¤
B<88>[(<81>Ð<90>U^@^@@^@^@<87>Ax^T<84><8a>A^H!<84>%=X<92><83>'=^H!<84><88>9x^T<84>iA^H!<84>^PB^H!<84>^PB^H!<84>E9h<92><83>'A^H^]<84>ã08^L<83>å8ø^\<84>E9X^P<83>'Aè
<84>^OB¸<9a><83>¬9^H!<84>$5HP<83>^F9è^\<84>Â,(<8a><82>Ä0¸^V<84>^D5(<8c><82>ä0ÈÔ<83>^KB<88><9a><83>I5ø^Z<84>gAx^V<84>iA^H!<84>$AH<90><83>^FAÈ^X<84>FAX<92><83>^F9¸^T<84>ËA¨^Z<84>*9^H^_<84>
4d^U^@<90>^@^@ ¢(<8a>¢(
^P^Z²

**Comment by ghaiklor** [comment]
Yes, I definitely not going for fields like above. There is a specification for such things - http://wiki.shoutcast.com/wiki/SHOUTcast_2_(Ultravox_2.1)_Protocol_Details#Metadata

Seems like radiostation you were trying to get info from is using something different. Feel free to play around with it and add support for parsing these cases as well.

**Comment by ghaiklor** [comment]
@carylewis got free time to investigate further and that is what I've found out.

Parser sends a request with `Icy-MetaData` header to indicate the radio station that I'm ready to accept the metadata

It responds with the following headers:

```js
{
  'content-type': 'application/ogg',
  date: 'Sun, 20 Sep 2020 12:39:40 GMT',
  'icy-br': '96, 96',
  'ice-audio-info': 'channels=2;samplerate=44100;bitrate=96',
  'icy-description': 'DJ-mixed blend of modern and classic rock, electronica, world music, and more. Always 100% commercial-free',
  'icy-genre': 'Eclectic',
  'icy-name': 'Radio Paradise (96k Ogg/Vorbis) - playlist: radioparadise.com',
  'icy-pub': '1',
  'icy-url': 'https://radioparadise.com',
  server: 'Icecast 2.4.0-kh14',
  'cache-control': 'no-cache, no-store',
  'access-control-allow-origin': '*',
  'access-control-allow-headers': 'Origin, Accept, X-Requested-With, Content-Type, Icy-MetaData',
  'access-control-allow-methods': 'GET, OPTIONS, HEAD',
  connection: 'Close',
  expires: 'Mon, 26 Jul 1997 05:00:00 GMT'
}
```

The thing here is... it does not have an `icy-metaint` response. This field is used to indicate the offset of where the metadata is expected to be. Without it, I don't know how many bytes I need to skip before parsing the metadata itself.

So, specifically in your case, the problem is on the radio side. I've added a note to the readme to indicate, that the radio station must support `Icy-MetaData` header to work.
