### ISSUE TITLE
How to obtain all the metadata content besides the "streamTitle".

### ISSUE THREAD

**Issue by BryonConley** [ghaiklor/icecast-parser#168]
Hi,  Firstly, thank you for developing this module.   I've gone through the documentation & example codes but didn't find what I was looking for.   In your "simple" code example, you use metatadata.streamingTitle to print this piece of metadata to the console.  I have a number of questions so that I can  possibly integrate this module into my project.   Here are the questions:
1. You used streamTitle as an example which is fine for that example, however, I would like to know all the metadata object names besides streamTitle.  Is there a way to tell this method to print out the name of all the metatdata names the has been collected successfully?  Incling CoverArt and other items.   I ask this as my current stream is SHOUTCast and their metadata specification labels doesn't seem to many the streamTitle item you used as an example.
2. As part of my project, I'd like to pass the values of the miscelaneous metadata objects as values into the rest of my application.  For instance I'd like to pass the coverArt to be displayed if it exists.  song duration, artist name, and other tagged items that are used in the SHOUTCast.
3. I'd also like to pipe the output of the .stream item into another  component in my app which will basically play the audio, or in separate id3 metadata parser.   When I pipe the stream to an id3 parser, the keeplisten: true does not seem to keep the connection but drops out.  What should I be aware of that could case the connection to 'end'.
4.  FInally, I noticed another user had the same question,  can this module be configured to only update all the metadata only when songs are changed or changein metadata content.  For instance, are there any triggerable events that this module can observve and trigger an event to "collect" the metadata?

Also, if you find my questions useful to others, would you update the Readme and and additional code examples?
Just my observations as a newbie to JS.  Thanks again for the time reviewing in advance.

**Comment by ghaiklor** [comment]
1. When you are getting the metadata it is an object with all the data it could parse. Just use `Object.keys` if you want to get a list of data there.
2. Not sure I understand what you want to achieve. This module is just a parser from existing streams. It has nothing to do with something more than that.
3. You can try to subscribe to `error` events, maybe something is broken and you will get the error why. `keepListen` should be enough and you can see that in some examples.
4. It is a work in progress here #165. You will specify a flag that change behaviour to "notify only when data was changed".

**Comment by BryonConley** [comment]
HI Eugene, thank you for this reply.  perhaps a clarification is in order.  I am using the simple.js example scrript you provided in the icecast-parser package.  I noticed you used StreamingTitle as the key to print the value to the console.log function.   I did do the Object.keys(metadata)  and only see the StreamingTitle key on the object metatadata you created and populated it with the key of StreamingTitle and value.   Is ICECast parser only picking  and assigning StreamingTitle?    I can confirm the shoutcast streaming we have running is indeed sending other metadata elements.  I can prove it by using our address "http://wshs4u-panel.com:14029/stream and point it to an HTML5 radio player and I see image art along with other metadata elements.   How can I use this ICECast-parser to pickup all the metadata and populate the metadata object you defined with them?   
What I intend to do is take the ICEcast=parser as the front end to collect all the metadata and take the stream output (as you have in one of your examples) and pipe it to a streaming audio player so I can create an app on android and ios while displaying all the relevan object collected by your metadata object including album art image etc.   Thanks again Eugene for you prompt reply on this and I look forward to have my project up and running.

**Comment by ghaiklor** [comment]
It is possible that the stream is using some other format to stream the metadata. This library is parsing only the protocol known as ICECast - https://gist.github.com/ePirat/adc3b8ba00d85b7e3870.

**Comment by ghaiklor** [comment]
@BryonConley I'm gathering the feedback and going through issues at the moment. Can you clarify some questions in case you still have one? Before asking, update to the latest `4.0.1` version, though. I've simplified some of the things, improved back and forth, etc... Could be that the latest version is what you want?

**Comment by ghaiklor** [comment]
Closing this one due to author inactivity. The answer here, when the event `metadata` arrives it has a `Map` with all the metadata that radio gives to the parser. You can take it by calling `keys()`, `values()` or `entries()` on the Map.

If something is missing, it means that the radio does not pass it through the stream or request, but in some other ways that is out of scope for this package.
