### ISSUE TITLE
Unexpected Token "."

### ISSUE THREAD

**Issue by Myzumi** [ghaiklor/icecast-parser#170]
**Describe the bug**
Crashing on startup

**To Reproduce**

1. Use the parse onces

**Expected behavior**
That it would work

**Additional context**

https://prnt.sc/uzj85b

Code:
```javascript
    const readiostream = new reader.Parser({
        url: 'http://stream.animeradio.de/animeradio.ogg',
        autoUpdate: true,
        keepListen: true
    })
    readiostream.on('metadata', (metadata) => {
        console.log(metadata)
    })
```

**Comment by ghaiklor** [comment]
This module works only on Node.js >= 14

https://github.com/ghaiklor/icecast-parser/blob/73be9b634ce7b6803c8dad1e0033653c950a4395/package.json#L20-L22

**Comment by Myzumi** [comment]
Ok thanks, didnt really know that my node version was outdated

just got one last question, im trying to get the infomation out of this url http://stream.animeradio.de/status.xsl and would ask how exactly do i use it? like what link do i need to use for it as the link itself dosent work and not want to open a new issue for it

**Comment by ghaiklor** [comment]
You need to provide the link to the stream of the radio station. Check the documentation
