### ISSUE TITLE
Icecast-parser fails to run out-of-the-box tsc and node

### ISSUE THREAD

**Issue by BryonConley** [ghaiklor/icecast-parser#171]
**Describe the bug**
The icecast-parser-master I downloaded yestereday Nov 28, 2020 onto my workspace with node and typscript already glabally installed fails to run the 'simple' testcase right out of the box.   A couple issues  were detected right away before starting -- no presence of ;s or mjs files in this zipped package -- all ts files even though the Github summary sayss it is anodejs package.
Secondly,  I used tsc to compile the simle.ts file after entering my radiostation url failed with basic un-runnable issues such as the import Parser from '..';  -- this doesn't compile as directories are not allowed, so modifiying this to import Parser from '../src/Parser';  at least got further in tsc compile with these error messages:

$ tsc simple.ts
../src/Parser.ts(3,9): error TS1192: Module '"http"' has no default export.
../src/Parser.ts(4,9): error TS1192: Module '"https"' has no default export.
../src/Parser.ts(118,32): error TS2569: Type 'IterableIterator<[string, string]>' is not an array type or a string type. Use compiler option '--downlevelIteration' to allow iterating of iterators.
../src/StreamReader.ts(18,47): error TS2550: Property 'matchAll' does not exist on type 'string'. Do you need to change your target library? Try changing the `lib` compiler option to 'es2020' or later.

I went ahead and  added es2020 into the lib for the tsconfig.json did improve 'string' issues, but resulted in the a above errors.

I've tested an older version of this package some 7 months ago and that package same name almost runs right out of the box.  in that version you used 'const Parser = require();   I was able to get that version of events.js and simple.js to run after taking about 1/2 to debug and fix.  

Unlike the previous version,  I cannot get this package to run the examples.

What would be helpful, is to list dependencies,  procide documentation and assumptions expected in order to run the examples right out of the box.

I understand this is an Icy only parser,  however, I've used the older package to capture streaming ID3V2 metadata with ID3V2-parser integrated in the stream event option.   I'd like to see if I can get this to work here too.   

I am hoping thise version has the capability to report streamingTitle and othere data when songs change on the sreaming shoutcast station I am using for testing/.

**To Reproduce**
I am not sure this and below fline items is helpful because of the first step failure and no documentation in the readme on what assumptions and dependencies.  I've ran many other Gitub packages which for the most part worked out of the box.  So, I would not call myself a newbie, but I am not an expert either...

1. tsc simple.ts
2. Fails on import dir path not allowed
3. changed import Parser frum '..'; to import Parser from '../src/Parser'; got past the one failure
4. re-ran tsc simple.ts
5. received the above tsc errors -  went to Parser.ts and put {} around import { http } and [ https } 
6. after re-running tsc simple.ts after edit for {} in imports - stated addional errors wrt http and https.

Also received  tsc error stating Iterator<stromg>,<string> is not tyle array.

So as you can see,  this isn't going to play nicely on the tsc compile -- even after inserting es2020.string in the lib options for compile options as suggsted.

**Expected behavior**
I expected to have something that compiles and run like:
node  simple.js (after tsc successfully compiles)
Shoult pring streamingTitle, whether in an infinite loop ever 5 seconds, or have it watch for changes in streamingTitle and prints it when song  mp3 tracks change under Shoutcast mp3 stream.

In my specific case, I have a song loaded for debug purpose that has the following format:
"album - artist - title.mp3"  where the album may have the following string format:
1. simply the album name;
2. Control tokens like Promo:Album Name, Sponsor:Album name; Logo:Album name; Banner:Album name;

I can test by going to : http://whsh4u-panel.com:14083/stream or 14029
then I intended to make the song request from our rockitbroadcasting.com/troprock or americana to request the song title Frosty and artist "Major Tom" to test our token control app we've built.  We intend only to use the icasecast-parser as a separate monitor to make sure streamingTitle reflects the song file name correctly.

**Additional context**

**Comment by ghaiklor** [comment]
@BryonConley thanks for the detailed report!

I believe all the issues comes from TypeScript configuration. Did you override `tsconfig.json` with something? Because in my case everything works out of the box:

```
git clone repo.git
npm install
npm run build
npx ts-node example/simple.ts
```

**Comment by BryonConley** [comment]
HI Eugene,  Okay,  I ran a number of times trying 'this or that' . Without any tsconfigurations override my tsc fails with error messages to the effect ES2020 lib settings are needed with .string.  After  googling this and landed on stackoverflow  issue someone else had issues of similar error message ang they gave a solution to put int  the tesconfig file.  After doing this, I got different errors that I pasted in this issue ticket.  It would be helpful if you include the tsconfig file settings/overrides you have in your working code so all of us can use it out of the box.  Please find the below content of my tsconfig file and you'll see what issues they  solved only to get different issues:
"compilerOptions": {
    "lib": ["es2020.string"],
    "allowSyntheticDefaultImports": true
}

**Comment by ghaiklor** [comment]
@BryonConley I mean, `npm install && npm run build` right after `git clone` works just fine. You don't need to do anything at all. The fact it is happening for you indeed strange, but the code in the repository is working with no additional setup needed.

**Comment by ghaiklor** [comment]
Closing as stale.
