### ISSUE TITLE
Stop cast

### ISSUE THREAD

**Issue by dowhiletrue** [ghaiklor/icecast-parser#186]
I would like to stop streaming the audio and start listening to another radio station.

What I've tried so far: `stream.unpipe();`

Not sure whether this all that needs to be done to gracefully stop `Parser` without creating memory leaks before creating a new instance of `Parser`

**Comment by ghaiklor** [comment]
@dowhiletrue maybe you could disable the `autoUpdate`? https://github.com/ghaiklor/icecast-parser#configuration

**Comment by dowhiletrue** [comment]
Thanks @ghaiklor for your help!

Ended up using `keepListen: true`, `autoUpdate: false` as config and executing `stream.unpipe()`, `stream.destroy()` to stop the stream, before creating a new `Parser`for stream and metadata

**Comment by ghaiklor** [comment]
Closing the issue as resolved then, thanks!
