### ISSUE TITLE
notifyOnChangeOnly ignore UTC data

### ISSUE THREAD

**Issue by Beastlybear2017** [ghaiklor/icecast-parser#198]
When using `notifyOnChangeOnly: true`, if the stream passes `UTC` data, the metadata event is triggered due to the change in time between requests causing a *false* update which essensially ignores the `notifyOnChangeOnly` option.

Would it be possible/resonable to make it so that the `UTC` data does not trigger the `metadata` event?

Or preferably change the functionality to be able to add a list of metadata to cause the update such as `notifyOnChangeOnly: ['StreamTitle']` - This example only triggering the event when there is a change in the stream title.

**Comment by ghaiklor** [comment]
@Beastlybear2017 the project is open for contributions. Feel free to implement this and open a PR, and we will talk it through there.
