### ISSUE TITLE
Question marks instead of some characters

### ISSUE THREAD

**Issue by EvgeniyDoctor** [ghaiklor/icecast-parser#200]
**Describe the bug**
I have a track which has "Tiësto" as an artist tag. But after `metadata.get('StreamTitle')` i see "Ti�sto".
If i see info of this track the name is correct; if i just try to output it in the console or on the website - everything works fine until `metadata.get`. I already tried change encoding to utf8 for string or set header - no luck.

**To Reproduce**

1. just have a track with weird characters in tags

**Expected behavior**
I should see "Tiësto" as a result of `metadata.get('StreamTitle')`.

**Additional context**
```
const icecast = require('icecast-parser')
...
app.post('/ajax/meta', (req, res)=>{
	const radio = new icecast.Parser({
		url: req.body.url,
		autoUpdate: false,
	})
	radio.on('error', function(err){
		res.jsonp({status: false, errcode: err.code})
	})
	radio.on('metadata', (metadata) => {
		let meta = metadata.get('StreamTitle') // already "Ti�sto"
		res.jsonp({status: true, title: meta})
	})
})
```

**Comment by ghaiklor** [comment]
@EvgeniyDoctor feel free to add a test case for this specific case of yours in the parser via PR, and I'll take a look

**Comment by EvgeniyDoctor** [comment]
Problem was in some config, not in this library.
