### ISSUE TITLE
Error when module load

### ISSUE THREAD

**Issue by adivincent** [ghaiklor/icecast-parser#29]
Hi,

I have the error below when module load:
node_modules/icecast-parser/lib/index.js:31
f (typeof superClass !== "function" && superClass !== null) { throw new TypeEr
                                                                    ^
TypeError: Super expression must either be null or a function, not object

This error occured when I uncomment this line:
var icecast_parser = require('icecast-parser');

Do you know how can I solve this error ?

Best regards

**Comment by ghaiklor** [comment]
@adivincent which version of node you have ?

**Comment by adivincent** [comment]
@ghaiklor I have this version : v0.10.45

**Comment by ghaiklor** [comment]
@adivincent could you clone this repository and run tests under your current version of node ?

``` shell
git clone ...
npm install
npm test
```

**Comment by adivincent** [comment]
@ghaiklor I have some errors during complation....

> speaker@0.3.0 install /.../public_html/node_modules/icecast-parser/node_modules/speaker
> node-gyp rebuild

make: Entering directory '/.../public_html/node_modules/icecast-parser/node_modules/speaker/build'
  CC(target) Release/obj.target/output/deps/mpg123/src/output/alsa.o
../deps/mpg123/src/output/alsa.c:19:28: fatal error: alsa/asoundlib.h: No such file or directory
 #include <alsa/asoundlib.h>
                            ^
compilation terminated.
deps/mpg123/output.target.mk:103: recipe for target 'Release/obj.target/output/deps/mpg123/src/output/alsa.o' failed
make: **\* [Release/obj.target/output/deps/mpg123/src/output/alsa.o] Error 1
make: Leaving directory '/.../public_html/node_modules/icecast-parser/node_modules/speaker/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.14.32-xxxx-grs-ipv6-64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /.../public_html/node_modules/icecast-parser/node_modules/speaker
gyp ERR! node -v v0.10.45
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm ERR! Linux 3.14.32-xxxx-grs-ipv6-64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v0.10.45
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE

npm ERR! speaker@0.3.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the speaker@0.3.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the speaker package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs speaker
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls speaker
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /.../public_html/node_modules/icecast-parser/npm-debug.log

Below the result of npm test:

> icecast-parser@0.0.0-semantic-release test /.../public_html/node_modules/icecast-parser
> babel-node ./node_modules/.bin/isparta cover _mocha

npm ERR! Test failed.  See above for more details.

In attatch you can see the npm-debug log.

Best regards
[npm-log.txt](https://github.com/ghaiklor/icecast-parser/files/319937/npm-log.txt)

**Comment by ghaiklor** [comment]
@adivincent you need to install `libasound2-dev` package for your OS.

**Comment by adivincent** [comment]
@ghaiklor 
Hi,

I tried to install libasound2-dev and I tried to update nodejs to version 0.12.0. But icecast-parser doesn't work :( !
I tried to compile icecast-parser from the repository but I have some errors. You can see these errors in [npm-install.txt](https://github.com/ghaiklor/icecast-parser/files/322918/npm-install.txt)
 and [npm-test.txt](https://github.com/ghaiklor/icecast-parser/files/322920/npm-test.txt).

I tried to install icecast-parser with npm install icecast-parser but I got this error:
Missing error handler on `socket`.
TypeError: undefined is not a function
    at RadioParser.setConfig (/.../node_modules/icecast-parser/lib/index.js:204:36)
    at new RadioParser (/.../node_modules/icecast-parser/lib/index.js:64:13)
    at Socket.<anonymous> (/.../server_chat/server_chat.js:521:23)
    at Socket.emit (events.js:107:17)
    at Socket.onevent (/.../node_modules/socket.io/lib/socket.js:335:8)
    at Socket.onpacket (/.../node_modules/socket.io/lib/socket.js:295:12)
    at Client.ondecoded (/.../node_modules/socket.io/lib/client.js:193:14)
    at Decoder.Emitter.emit (/.../node_modules/socket.io/node_modules/socket.io-parser/node_modules/component-emitter/index.js:134:20)
    at Decoder.add (/.../node_modules/socket.io/node_modules/socket.io-parser/index.js:247:12)
    at Client.ondata (/.../node_modules/socket.io/lib/client.js:175:18)

Now I have this error on this code : 
audioStream = new icecast_parser({
            url: data.url_stream,
            keepListen: false, // don't listen radio station after metadata was received
            autoUpdate: true, // update metadata after interval
            errorInterval: 10 \* 60, // retry connection after 10 minutes
            emptyInterval: 5 \* 60, // retry get metadata after 5 minutes
            metadataInterval: 5 // update metadata after 5 seconds
        });

```
    audioStream.on('metadata', function(metadata){
        if (metadata.StreamTitle == '')
        {
            metadata.StreamTitle = DefaultStreamTitle;
        }

        metadata.error = false;

        socketsUser['uid'+data.uid_from].emit('retrieveAudioStreamInfo', {metadata : metadata, url_stream: data.url_stream});
    });

    audioStream.on('empty', function(){
        metadata = {
            StreamTitle : DefaultStreamTitle,
            error: false
        };

        socketsUser['uid'+data.uid_from].emit('retrieveAudioStreamInfo', {metadata : metadata, url_stream: data.url_stream});
    });

    audioStream.on('error', function(error) {
        metadata = {
            StreamTitle : DefaultStreamTitle,
            error: error
        };

        socketsUser['uid'+data.uid_from].emit('retrieveAudioStreamInfo', {metadata : metadata, url_stream: data.url_stream});
    });
```

And not this : var icecast_parser = require('icecast-parser');

Thank you for your help.

Best regards

Vincent

**Comment by ghaiklor** [comment]
@adivincent 0.12 that's too old. Install the latest version of NodeJS.

**Comment by adivincent** [comment]
@ghaiklor I update my NodeJS to the latest version and it works. Thank you for your help.

Best regards
