### ISSUE TITLE
Is it possible to use it in browser?

### ISSUE THREAD

**Issue by arkdy** [ghaiklor/icecast-parser#7]
Hello,
I want to read icecast metadata in client-side application.
If it's possible, tell me please how can I use your library in browser.
Thanks!

**Comment by ghaiklor** [comment]
@ashrayer I've developed this library only for NodeJS using Stream API. There is no possibilites to run it in browser.

**Comment by chriscoderdr** [comment]
You could use it in your backendand and have a rest endpoint/api
