### ISSUE TITLE
FR: Autoupdate only when changed.

### ISSUE THREAD

**Issue by timrijckaert** [ghaiklor/icecast-parser#82]
Hi, 

Nice work on this lib.

This will be more of a feature request.
I noticed you use a simple interval mechanism to pull metadata changes. 
However it would be nice if you could have an `autoupdate` feature that only triggers when the previous metadata changed.  
Something like `RxJs scan` [operator](https://github.com/Reactive-Extensions/RxJS/blob/master/doc/api/core/operators/scan.md) 

Thanks

**Comment by ghaiklor** [comment]
WIP #165

**Comment by ghaiklor** [comment]
Published in `v4.0.1`

**Comment by ghaiklor** [comment]
For reference, how does it look like

<img width="1904" alt="Screen Shot 2020-09-20 at 18 21 39" src="https://user-images.githubusercontent.com/3625244/93714875-31480800-fb6e-11ea-9214-daa43b66d23f.png">
