### ISSUE TITLE
Stream timeout

### ISSUE THREAD

**Issue by motiejunas** [ghaiklor/icecast-parser#93]
My application listens for ~30 radio streams and the goal is to run the application for weeks.

Sadly, some streams stops after some time.

For example:
http://84.46.162.57:8000/ehr (stops after 12 hours, other streams seems to be stoping at random intervals)

I didn't get any error event and it does not auto refresh with errorInterval... I was also using another library and had exactly the same issue.

`
const stream = new Parser({
      url: 'http://84.46.162.57:8000/ehr',
      keepListen: true,
      metadataInterval: 1
    });
`

My initial thought is to catch more events such as timeout/finish/close...?

**Comment by ghaiklor** [comment]
@motiejunas you said that the issue reproduces with other libraries as well. As for me, it's the hint that the issue could be with radiostation itself. Can be, that they are shutting down sometimes ?

**Comment by motiejunas** [comment]
The station keeps running all the time but I believe that it has some timeout after 12 hours of non-stop listening to kick listener. If I manually restart this radio station it works again for 12 more hours and stops again. I want to prevent manual restarting and receive some event when stream stops.

Also similar issue appears for other stations as well, just at random interval. The goal is to keep alive forever without manual restart.

**Comment by ghaiklor** [comment]
@motiejunas did you try to listen for `error` event ? Theoretically, if you're trying to connect to radiostation that can't respond, it should emit error event.

**Comment by motiejunas** [comment]
Sure, but `error` event does not return anything in this case, that's why I am worrying. If I could catch it through `error` event I could easily restart the stream and everything would be OK, but for now I am not able to detect when stream stops.

**Comment by ghaiklor** [comment]
@motiejunas well, it's definitely looks like enhancement. Do you want to participate in it and help with development? Cause, while I was developing the package I didn't see such behavior and I'm afraid I can't reproduce it in few minutes.

**Comment by ghaiklor** [comment]
@motiejunas there was an improvement, that adds a new event `end`
