### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by chriscoderdr** [ghaiklor/icecast-parser#97]
Just cloned the repo and ran tests and I got error without any modifications:
$ istanbul cover _mocha
 5   -_-_-_-_,------,
 1   -_-_-_-_|   /\_/\ 
 0   -_-_-_-^|__( x .x) 
     -_-_-_-  ""  "" 

  5 passing (10s)
  1 failing

  1) RadioParser
       Should properly emit metadata from Icecast:
     Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.

the culprit seems to be that the url in the tests http://online-kissfm.tavrmedia.ua/KissFM_deep it's returning 404 - The file you requested could not be found

**Comment by chriscoderdr** [comment]
BTW Maybe mocking the icecast server would be in our best interests given that that way test won't fail just because the server is down, only when the code is actually failing.

**Comment by ghaiklor** [comment]
@cgomezmendez agreed with that, I didn't have time for it, so went with trivial solution.

Need to make it with own mock server for radiostations or just use mocks and stub.
